### PR TITLE
fix: shortest path crash with zero-length weight vector

### LINKED ISSUE #513: Weighted shortest_paths crashes on edgeless graphs.
**Describe the bug**
Running `shortest_paths` with the `weights` parameter on an edgeless graph triggers the fatal error and crashes python: `Fatal error at src/core/vector.c:1181 : Assertion failed: v->stor_begin != v->end`

**To reproduce**
```python
>>> import igraph
>>> g = igraph.Graph()
>>> g.add_vertices(1)
>>> g.es['attr'] = []
>>> g.shortest_paths(weights='attr')
```

**Version information**
Crashes in 0.9.9.
Also tested in 0.7.1.post6, everything works fine.

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #513.

This is trivial, but I'm not yet comfortable directly committing to python-igraph

### CODE REVIEW

**Comment by szhorvat** [comment]
I checked, and could not find any other similar problems in the python-igraph codebase.

**Comment by iosonofabio** [comment]
Would you mind changing the comment of line 5833 into:

```
/* No weights or empty weight vector, use a simple BFS */
```

**Comment by iosonofabio** [comment]
Then you can merge

**Comment by szhorvat** [comment]
Merged. I'll leave the `master` -> `develop` merge to you, in case some conflict appears that I wouldn't be comfortable resolving.

**Comment by ntamas** [comment]
Merged into `develop`

**Pull request merged**
