### PR TITLE
Bring tutorial and documentation up to date.

### PR DESCRIPTION
**Pull request by jboynyc**
In response to the request in issue #93, I thought I would take a few stabs at updating and improving the tutorial. Here's a first set of edits.

### CODE REVIEW

**Comment by vtraag** [comment]
Hi @jboynyc! Thanks for the edits! To be sure: you are planning on committing more? If so, just let us know when you would like us to take a closer look. FYI: I assume you noticed that a new version of `python-igraph` was just released (version 0.8.0), including binaries from PyPI for all platforms? There may be some differences with earlier versions throughout the documentation.

For the next time, you can also mark your PR as a [draft PR ](https://github.blog/2019-02-14-introducing-draft-pull-requests/) (recently learned about that myself actually), but for now we can simply stick to this.

**Comment by jboynyc** [comment]
Yes, I saw. Congrats @vtraag and team! Exciting times.

I will make more edits, also to some other parts of the documentation. Good idea to use a draft PR that I add commits to rather than making a bunch of separate PRs. (The feature was new to me, too.)

**Comment by vtraag** [comment]
> Yes, I saw. Congrats @vtraag and team! Exciting times.

Thanks!

> I will make more edits, also to some other parts of the documentation. Good idea to use a draft PR that I add commits to rather than making a bunch of separate PRs. (The feature was new to me, too.)

OK, great to hear you will also be editing some other parts of the documentation! Note that you can also simply push new commits to this PR (as it also says here below): 

Add more commits by pushing to the `update-tutorial` branch on `jboynyc/python-igraph`.

**Comment by jboynyc** [comment]
> Note that you can also simply push new commits to this PR (as it also says here below):

Oh right, that's what I'll do then. (I haven't used GitHub for collaboration in a while, so I forgot some of the ins and outs.)

**Pull request merged**
