### PR TITLE
improve from_networkx performance

### PR DESCRIPTION
**Pull request by szhorvat**
This attempts to address #401.  It only fixes `from_networkx`, not `from_graph_tool`. I need some feedback before proceeding. I don't really know much Python, and this was merely an exercise for me. Take a very careful look before merging.

### CODE REVIEW

**Comment by szhorvat** [comment]
Benchmark:

```
import random
random.seed(123)
g = nx.gnm_random_graph(1000,10000)
```

then in ipython,

```
%timeit ig.Graph.from_networkx(g)
```

The speedup is from ~2.0 seconds to ~12 milliseconds.

**Comment by szhorvat** [comment]
I notice that the name `Graph.from_networx` seems inconsistent with other graph constructors, all of which are capitalized. Shouldn't this be corrected?

**Comment by szhorvat** [comment]
Why is the test for this functionality in `src/igraph/test` while everything else is in `tests`? Is this test run when doing `python -m unittest` as in the instructions?

Originally I messed up and forgot to convert vertex names to IDs, yet tests did not seem to fail. Assuming I ran the tests correctly, the tests should be improved to catch this mistake.

**Comment by ntamas** [comment]
> I notice that the name Graph.from_networx seems inconsistent with other graph constructors, all of which are capitalized. Shouldn't this be corrected?

The capitalization is a leftover from the early days of the development of the Python interface where I thought this would be a good idea to distinguish class methods from "normal" methods. Nowadays I don't use this convention in new code and prefer normal `underscore_case` instead. When we re-design the `python-igraph` API in the future such that we won't have a monolithic `Graph` class any more, this inconsistency will probably not be relevant any more. Until then, we can alias `from_networkx` with `From_Networkx` if we want to. Opinions?

> Why is the test for this functionality in `src/igraph/test` while everything else is in tests? 

Because I probably forgot to move them when I switched from the tests-within-the-package layout to the tests-outside-the-package layout [as advocated here](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) :) It should be in `tests` by all means.

**Comment by ntamas** [comment]
Thanks a lot!

**Comment by szhorvat** [comment]
> Until then, we can alias `from_networkx` with `From_Networkx` if we want to. Opinions?

No preference from me, just want to note that if this is done, it should be `From_NetworkX` and not `From_Networkx`.

**Comment by iosonofabio** [comment]
Thank you. Let's not rename and break API and also go against Python conventions.

**Pull request merged**
