### PR TITLE
Ignore .DS_Store

### PR DESCRIPTION
**Pull request by h5jam**
Hi ! I'm working on #467.

It would be good to ignore .DS_Store created by the macOS.
Would it be okay to insert in the last line? 

Thank you.

### CODE REVIEW

**Comment by szhorvat** [comment]
It's probably useful to do this, I just wanted to note that you can also set up your own personal ignore file which applies to all your repos:

https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by h5jam** [comment]
Okay, thanks for advising me. I confirmed it !

**Comment by szhorvat** [comment]
I am not the one to make a decision about merging this PR. I just wanted to give a hopefully helpful suggestion.

**Comment by h5jam** [comment]
I thought this PR was rejected.

Then, I want to get opinions from other contributors including a maintainer.

**Comment by ntamas** [comment]
Seems totally fine for me.

**Pull request merged**
