### PR TITLE
Tutorial for topological sort

### PR DESCRIPTION
**Pull request by h5jam**
Hi !  I'm Seung-oh, a junior from South Korea.

I got inspired by #460 to make compact tutorial. And I added topological sort example as a first contribution to participate this interesting project, python-igraph.

I need some reviews about my first small work.

### CODE REVIEW

**Comment by iosonofabio** [comment]
Thank you for the contribution. I changed this into a draft PR until it's good for prime time.

A few comments:
1. Please check your English grammar, esp. use of articles and prepositions. Sorry for not providing more detailed feedback, but time doesn't allow
2. your PNG seems to lack the lately added centering of vertex labels (c2a4843) and looks odd. Please remake the PNG with centered vertex labels
3. It's be great if you could add a sentence or two about why topological sorting is important and how it relates to DAGs.

Do you want to add a few more tutorials instead of just this one?

**Comment by h5jam** [comment]
Thank you for reviewing my work.

1. I will check with colleagues. (sorry for incorrect English grammar..)
2,3. I can try them.

Maybe an additional example will be add to this PR with colleagues.

**Comment by iosonofabio** [comment]
Hi guys,

Two quick suggestions:

1. I can see that several of you are pushing into the same PR branch. That is generally not a great idea, because you risk conflicting updates. It also makes it a little difficult from our end to help you if we don't know who's "in charge" of the PR. Instead, I think it would be a better idea for each of you to open a separate PR, and that each PR touches distinct files with no overlap between them.

2. In general, new tutorials are always welcome. It is important, however, that they are written in proper English (hopefully we can add more languages in the future!) so that the readers can understand properly. If you guys are working together as a team, then please make triple sure that the explanations are clear to an English-speaking audience, including spelling and grammar. It would be a pity if you worked on this for a long time and it got rejected at the end because of a few grammar mistakes.

Cheers,
Fabio

**Comment by ntamas** [comment]
@iosonofabio Can I assign this PR officially to you or shall I take care of it?

**Comment by iosonofabio** [comment]
Please do the following:

- merge `develop` into this PR
- check your English grammar again
- add to the `py` and `rst` files the code to make the plot

**Comment by h5jam** [comment]
I tried to write better sentences and included codes about generating a plot. Thanks for managing my PR.

**Comment by iosonofabio** [comment]
Hi @h5jam , I fixed a bunch of things. I'll merge this PR now, thank you for your contribution.

If you wish to make other tutorials, we'd be really grateful. However, in that case please look carefully at the changes I made to your PR to learn from your mistakes, in particular:

- English grammar and style. I know it's hard and unfair, but unfortunately necessary. A tutorial's whole point is **explaining**, and that requires fluency. If you don't want to deal with this perhaps make a PR that is NOT a tutorial :smirk:
- missing hyperlink in `gallery.rst`
- missing/broken hyperlinks to API functions
- code style: avoid long lines and check PEP8 for indentation rules
- merge `igraph/develop`
- try to differentiate your plot a little from existing ones, in this case I used the xkcd style

**Pull request merged**
