### PR TITLE
WIP: Tutorial gallery

### PR DESCRIPTION
**Pull request by iosonofabio**
igraph_gallery_screenshot

Code adapted from seaborn.

Good? No good? Comments? Suggestions?

### CODE REVIEW

**Comment by szhorvat** [comment]
Of course it's good!

I'd love to keep the aspect ratio of the figures intact if that easy, but unfortunately I can't offer a fix right now.

**Comment by szhorvat** [comment]
The maximum bipartite matching should have a much stronger contrast between thick and thin edges. I'll fix it later (unless someone else gets to it first).

**Comment by ntamas** [comment]
Here are [multiple solutions](https://stackoverflow.com/a/12912224/156771) for the aspect ratio problem.

**Comment by iosonofabio** [comment]
Alright, thanks. I was more wondering if we want to have a graphics-driven gallery at all or we prefer text.

It sounds like having thumbnails would be easier to browse than just a text list, so I'll spend a little more time on this. Don't worry about the exact figures, I'll standardize that one so it makes sense and looks good.

**Comment by szhorvat** [comment]
Yes, I think it would make sense.

**Comment by iosonofabio** [comment]
igraph_gallery_v2

This is coming along nicely, now with animated GIFs whenever there is one in the tutorial subfolder (currently only for the animated ring).

**Comment by iosonofabio** [comment]
Shall I just merge this?

If you want to test it, pull into a local branch and then:

```bash
./scripts/mkdoc.sh -t
```

**Comment by ntamas** [comment]
Let me take a quick look at this as there are conflicts with `develop` at the moment.

**Comment by ntamas** [comment]
I don't know why Github said that there are conflicts; it seems like there aren't any. Let me try this and then I'll merge.

**Comment by ntamas** [comment]
Thanks a lot, this is now merged!

**Pull request merged**
