### PR TITLE
Abandon Python 2 and lint black

### PR DESCRIPTION
**Pull request by iosonofabio**
Ambitious PR that abandons Python 2.7 and its idioms and lints the code to black.

What I did:
1. ran 2to3 on each file in `src/igraph` and subfolders
2. corrected a few things manually (mostly lazy iterators where 2to3 was too cautious)
3. deleted `compat.py` and deleted (`property`) or adapted (`BytesIO`) imports from it
4. deleted 2.7 and `use_2to3` from `setup.py`
5. deleted 2.7 and its special conditions in `tox.ini`
6. linted everything using the "black" PEP8 rules

Tests are passed on Python 3.9 on my machine, let's see what CI says. I will also lint and adapt the `tests` folder now.

@ntamas take your time, it's a beast

### CODE REVIEW

**Comment by ntamas** [comment]
Will do, thanks!

The official promise is that `python-igraph` 0.8.x is the last release series that still supports Python 2.7, so I might need to cut a final-final-final 0.8.x release with all the latest goodies in it before merging this.

Or, maybe not. We'll see.

**Comment by ntamas** [comment]
CI breakage has nothing to do with the PR. I think that the `zstd` package is needed so AppVeyor can deal with some of its own packages that are distributed as `.7z` files -- not sure. But there is a reason why it had to be installed.

Maybe upgrading to the latest AppVeyor image (if there is one) also helps.

**Comment by ntamas** [comment]
Also, if you don't mind lots of Python virtualenvs on your machine, `tox` does a pretty good job at testing `python-igraph` with multiple Python versions and we already have a `tox.ini` in the repo. Use `tox -e` to test with a specific Python version (use `py36`, `py37`, `py38` or `py39`), or just run `tox` to test everything on all versions.

**Comment by iosonofabio** [comment]
Awesome, I'll try putting a bunch of virtualenvs and see.

**Comment by ntamas** [comment]
CI is now fixed so you can rebase your PRs (or merge the `master` branch) if you want to get an up-to-date CI report.

**Comment by iosonofabio** [comment]
Thank you, i will

**Comment by iosonofabio** [comment]
Alright, I rebased now

**Comment by iosonofabio** [comment]
I think this is currently failing CI on Pypy2.7, which kind of makes sense since `appveyor.yml` excludes only:

```
CIBW_SKIP: "cp27-* cp35-*"
```

but not Pypy 2.7. Why on Earth that only happens with `TARGET_ARCH: "x86"` and not `"x64"` I don't know.

**Comment by ntamas** [comment]
Just did that, let's see how it goes.

Otherwise it looks good to me -- feel free to mark this as ready for review when you think it's good to merge.

**Pull request merged**
