### PR TITLE
Add aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added aarch64 wheel build support.
Related to https://github.com/igraph/python-igraph/issues/431, @ntamas Could you please review this PR?

### CODE REVIEW

**Comment by ntamas** [comment]
Thanks for the PR! Seems good to me; I'll let the jobs run now and see whether it works. If it does, I'll be happy to merge this.

**Comment by ntamas** [comment]
@odidev It looks like the aarch64 build is taking quite a long time in CI; do you happen to know whether this is normal?

**Comment by odidev** [comment]
> @odidev It looks like the aarch64 build is taking quite a long time in CI; do you happen to know whether this is normal?

@ntamas Yes. Because of QEMU, the AArch64 build takes longer time.

**Comment by ntamas** [comment]
Thanks @odidev! I just came back from holidays so I'll take a look at the PR soon.

I see that you recently force-pushed to this PR. Are you planning to migrate it to Azure or will it stay on Travis CI? For me Travis would have been great but I realized that they don't have an option to store the build artifacts along with the build (you can only give it an external AWS bucket to upload stuff to). So, if you stick to Travis, I'll happily merge it but the built wheels will be made available on PyPI only after a release (you won't be able to download any wheels built for non-tagged commits). I think Azure can keep the build artifacts available for a while so we can run the job on all commits and you can get wheels for any of the commits that are in `master`.

**Comment by vtraag** [comment]
Sorry, I thought that Azure was being used to build (`python`)-`igraph` in `conda-forge` for `aarch64`, but they are using Drone. This builds `igraph` in 6 minutes, so I guess that is using native `aarch64`.

**Pull request merged**
