### PR TITLE
Color Bar for Betweenness Tutorial

### PR DESCRIPTION
**Pull request by Gomango999**
Added color bars for both vertex and edge betweennness, as request [here](https://github.com/igraph/python-igraph/pull/486#issuecomment-999016137).

### CODE REVIEW

**Comment by iosonofabio** [comment]
Hmm, good intent but a little messy for now. Two points:

- Color bars need a name, you can't just put numbers out there, esp. if there are two
- It'd be better if they spanned the height of the graph, no more.

I'll take a stab at it at some point, feel free to improve before that if you want

**Comment by Gomango999** [comment]
Cheers, I'll have a go at making those changes.

**Comment by Gomango999** [comment]
Okay that was surprisingly difficult for what I wanted to do, but I've managed to get the color bars and labels displaying correctly now:

betweenness

**Comment by iosonofabio** [comment]
Hehe, your effort saves hundreds of people's efforts down the road 😉

**Comment by iosonofabio** [comment]
Aye, will look at this and merge tomorrow

**Comment by iosonofabio** [comment]
Changed the coding style here and there using gridspec and chomping endline spaces, improved wording a little bit too. Merging.

**Pull request merged**
