### PR TITLE
Conversion of objects to/from other libraries

### PR DESCRIPTION
**Pull request by iosonofabio**
This tries to address #237.

**Done**:
- Graph to/from networkx
- Graph to/from graph-tool
- Multigraphs to/from networkx
- Multigraphs to/from graph-tool

All these things include tests that pass locally. All tests on networkx pass on Travis too, but graph-tool is a pain to install there so that is not tested on CI.

**This is ready for merging now**

### CODE REVIEW

**Comment by ntamas** [comment]
FYI, this PR needs to be adjusted for the new directory structure (`igraph` moved under `src`).

**Comment by iosonofabio** [comment]
I now adjusted the PR as requested and pulled in a fresh version of the `master` branch. I am puzzled by the failure on AppVeyor though, it doesn't appear to be obviously related to this particular PR?

**Comment by ntamas** [comment]
Yes, that's unrelated, it is also present on the master branch. I have to look into this at some point, I just haven't found the time to do so yet.

**Comment by ntamas** [comment]
Thanks a lot! The CI tests should now pass as I fixed the MSVC build error in master.

**Pull request merged**
